version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    dir: cmd
    goos:
      - linux
      - windows
      - darwin

archives:
  - id: tar.gz
    format: tar.gz
  - id: binary
    format: binary
